### ISSUE TITLE
3rd party library import

### ISSUE THREAD

**Issue by vforv** [jkuri/angular-closure-compiler#2]
Hello,

Is it possible to import https://github.com/valor-software/ngx-bootstrap with google closure?

**Comment by jkuri** [comment]
could be possible, yes. whats the issue currently?

**Comment by vforv** [comment]
Here: http://stackoverflow.com/questions/44100512/how-to-implement-google-closure-and-ngx-bootstrap I am using closure.conf ...

Here is full conf:

```
--compilation_level=ADVANCED_OPTIMIZATIONS
--language_out=ES5
--js_output_file=dist/public/client.js
--output_manifest=dist/manifest.MF
--variable_renaming_report=dist/variable_renaming_report
--property_renaming_report=dist/property_renaming_report
--create_source_map=%outname%.map

--warning_level=QUIET
--dependency_mode=STRICT
--rewrite_polyfills=false
--module_resolution=node

node_modules/zone.js/dist/zone_externs.js


--js node_modules/rxjs/**.js
--js node_modules/ngx-bootstrap/ng2-bootstrap.js
--process_common_js_modules

node_modules/@angular/core/@angular/core.js
--js_module_root=node_modules/@angular/core
node_modules/@angular/core/src/testability/testability.externs.js

node_modules/@angular/router/@angular/router.js
--js_module_root=node_modules/@angular/router

node_modules/@angular/common/@angular/common.js
--js_module_root=node_modules/@angular/common

node_modules/@angular/platform-browser/@angular/platform-browser.js
--js_module_root=node_modules/@angular/platform-browser

--js built/**/**.js
--entry_point=./built/src/main.client

```

**Comment by jkuri** [comment]
what part of `ES6 transpilation of 'Wildcard export' is not yet implemented.` is not clear?
try including node_modules/ngx-bootstrap/**/*.js or something.

**Comment by vforv** [comment]
Hmm, it looks like it works now, thanks.

Just one more question where should I import bootsrap.css script, is there any way to handle this with closure?

**Comment by jkuri** [comment]
you welcome. you could put it in `index.html` as `<link rel="stylesheet" type="text/css" href="node_modules/ngx-bootstrap/path/to/bootstrap.css">`.

**Comment by vforv** [comment]
Now everything works, thanks very much
